fix: modify security exception-handling
SWM-REPL/gifthub-was pull request #96
Opened 2023-10-04 21:21 UTC by jinlee1703

### PR Type
- [ ] 기능 추가
- [ ] 기능 삭제
- [x] 버그 수정
- [ ] 테스트 코드 작성
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [ ] 문서 작성

### Motivation 

- FE의 401 및 403 에러 발생 시 예외 처리 형식 단일화 요청

### Problem Solving

- SecurityConfig 수정

### To Reviewer

- 현재 에러 코드는 400, response body의 `status_code`를 401 혹은 403으로 처리 중

	<img width="1282" alt="image" src="https://github.com/SWM-REPL/gifthub-was/assets/68031450/863815e8-a836-48f5-855a-7cb89fea2e02">

- 추후 API 응답 형식 수정 시 재수정 예정

2023-10-04 21:24 UTC, seheon99 reviewed
확인했습니다

2023-10-04 23:49 UTC, inh2613 requested changes
`reissueAccessTokenTest`에서 
``` java
mockMvc.perform(post("/auth/refresh")
						.header("Authorization", refreshToken))
				.andExpect(status().isUnauthorized());
```
`401`에러를 기대하고 있어서 CI 오류가 난 것 같습니다!

2023-10-05 00:21 UTC, jinlee1703 commented
> p2: `reissueAccessTokenTest`에서
> 
> ```java
> mockMvc.perform(post("/auth/refresh")
> 						.header("Authorization", refreshToken))
> 				.andExpect(status().isUnauthorized());
> ```
> 
> `401`에러를 기대하고 있어서 CI 오류가 난 것 같습니다!

감사합니다! 추후 응답 코드 수정 고려하여 다음과 같이 수정했습니다 :)
`.andExpect(status().is4xxClientError());`

2023-10-05 00:23 UTC, inh2613 approved these changes
LGTM

2023-10-05 00:23 UTC, merged